- name: "Create Docker yml "
  ansible.builtin.template:
    src: "docker_compose.j2"
    dest: "{{ monitoring_dir }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: '0644'

- name: "Start monitoring stack"
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ monitoring_dir }}"
  register: compose_up
  changed_when: "'Started' in compose_up.stderr or 'Recreated' in compose_up.stderr or 'Created' in compose_up.stderr"